name: Release

on:
  push:
    tags: v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.API_KEY_CF }}
      WOWI_API_TOKEN: ${{ secrets.API_TOKEN_WOWI }}
      WAGO_API_TOKEN: ${{ secrets.API_TOKEN_WAGO }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: BigWigsMods/packager@v2
